name: Build and Release Workflow

on:
  release:
    types:
      - published
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '21'  # 根据你的项目需要设置 Java 版本
          distribution: 'microsoft'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload release assets
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files:
            ./build/libs/*.jar
        
      
